# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w # strip symbols, reduces binary size
      - -X main.operatorversion={{.Version}}
      - -X main.operatorbuilddate={{.Date}}
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers:
  - image_templates:
      - "redradrat/aws-iam-operator:{{ .Tag }}-amd64"
      - "redradrat/aws-iam-operator:latest-amd64"
      - "ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:{{ .Tag }}-amd64"
      - "ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:latest-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--builder=desktop-linux"
    dockerfile: goreleaser_Dockerfile
  - image_templates:
      - "redradrat/aws-iam-operator:{{ .Tag }}-arm64"
      - "redradrat/aws-iam-operator:latest-arm64"
      - "ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:{{ .Tag }}-arm64"
      - "ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--builder=desktop-linux"
    dockerfile: goreleaser_Dockerfile
docker_manifests:
  - name_template: redradrat/aws-iam-operator:{{ .Tag }}
    image_templates:
      - redradrat/aws-iam-operator:{{ .Tag }}-arm64
      - redradrat/aws-iam-operator:{{ .Tag }}-amd64
  - name_template: redradrat/aws-iam-operator:latest
    image_templates:
      - redradrat/aws-iam-operator:latest-arm64
      - redradrat/aws-iam-operator:latest-amd64
  - name_template: ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:{{ .Tag }}
    image_templates:
      - ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:{{ .Tag }}-arm64
      - ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:{{ .Tag }}-amd64
  - name_template: ghcr.io/redradrat/aws-iam-operator:latest
    image_templates:
      - ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:latest-arm64
      - ghcr.io/redradrat/aws-iam-operator/aws-iam-operator:latest-amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env_files:
  # use only one or release will fail!
  github_token: ~/.tokens/goreleaser_github
