---
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: aws-iam-operator
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
      - "6"
    ldflags:
      - -s -w # strip symbols, reduces binary size
      - -X main.operatorversion={{.Version}}
      - -X main.operatorbuilddate={{.Date}}

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - redradrat/{{ .ProjectName }}:{{ .Tag }}-amd64
      - redradrat/{{ .ProjectName }}:latest-amd64
      - ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/redradrat/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.description="An operator that enables AWS IAM management via Kubernetes custom resources"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.url="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.authors="redradrat"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - redradrat/{{ .ProjectName }}:{{ .Tag }}-arm64
      - redradrat/{{ .ProjectName }}:latest-arm64
      - ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/redradrat/{{ .ProjectName }}:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.description="An operator that enables AWS IAM management via Kubernetes custom resources"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.url="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.authors="redradrat"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: "goreleaser.Dockerfile"
    image_templates:
      - redradrat/{{ .ProjectName }}:{{ .Tag }}-armv7
      - redradrat/{{ .ProjectName }}:latest-armv7
      - ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}-armv7
      - ghcr.io/redradrat/{{ .ProjectName }}:latest-armv7
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.description="An operator that enables AWS IAM management via Kubernetes custom resources"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.url="https://github.com/redradrat/aws-iam-operator"
      - --label=org.opencontainers.image.authors="redradrat"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"

docker_manifests:
  - name_template: redradrat/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - redradrat/{{ .ProjectName }}:{{ .Tag }}-arm64
      - redradrat/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: redradrat/{{ .ProjectName }}:latest
    image_templates:
      - redradrat/{{ .ProjectName }}:latest-arm64
      - redradrat/{{ .ProjectName }}:latest-amd64
  - name_template: ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/redradrat/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: ghcr.io/redradrat/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/redradrat/{{ .ProjectName }}:latest-arm64
      - ghcr.io/redradrat/{{ .ProjectName }}:latest-amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag}}-devel"

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: mod
  gobinary: go

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env_files:
  # use only one or release will fail!
  github_token: ~/.tokens/goreleaser_github
