---
name: Simple build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: 662412797287.dkr.ecr.eu-central-1.amazonaws.com
  REGISTRY_REPO: aws-iam-operator

  # if master branch, use latest tag, else use temp-{sha} tag
  TAG: ${{ github.ref == 'refs/heads/master' && 'latest' || format('temp-{0}', github.sha) }}

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - 'master'
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  Build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-central-1"
          role-to-assume: arn:aws:iam::662412797287:role/ECR_GithubRole

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: ${{ github.ref == 'refs/heads/master' }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_REPO }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/cache:${{ github.event.repository.name }}-buildcache
          cache-to: type=registry,image-manifest=true,ref=${{ env.REGISTRY }}/cache:${{ github.event.repository.name }}-buildcache,mode=max
